sonar.projectKey=jooservices_laravel-notifications
sonar.organization=jooservices
sonar.sources=src
sonar.tests=tests
sonar.php.coverage.reportPaths=build/coverage/clover-combined.xml
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/.github/**,vendor/**,coverage/**,build/**
